; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
lib_deps = 
	mathertel/OneButton@^2.6.2
	fastled/FastLED@^3.10.3
	makuna/DFPlayer Mini Mp3 by Makuna@^1.2.3
	esp32async/ESPAsyncWebServer@^3.12.0
	esp32async/AsyncTCP@^3.5.0
	electroniccats/MPU6050@^1.4.5

build_flags = 
	-DCORE_DEBUG_LEVEL=5

monitor_filters = direct

board_build.filesystem = littlefs

; Change to what YOUR specific situation
monitor_speed = 115200

monitor_port = COM8
upload_port = COM7